name: Release

on:
  workflow_dispatch:
    inputs:
      type:
        required: true
        type: choice
        description: Release type
        options:
          - patch
          - minor
          - major
          - previous
        default: 'patch'

      package:
        required: true
        type: choice
        description: Package to release
        options:
          - qwik-nx
          - create-qwik-nx

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - run: |
          [[ "${{ inputs.type }}" ]] || { echo "inputs.type input is empty" ; exit 1; }
        shell: bash

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [16]

    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: ${{ matrix.node_version }}

      - name: Test
        uses: ./.github/actions/test
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: [test]
    env:
      NPM_CONFIG_PROVENANCE: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup

      - name: Release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpx nx run ${{ inputs.package }}:version-publish --configuration=${{ inputs.type }} --push=true

      - name: Tag last-release
        if: github.ref == 'refs/heads/main'
        shell: bash
        run: git tag -f last-release

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
          tags: true
